site_name: Engineering Notebook
site_url: http://engineering-notebook.readthedocs.org
site_description: Engineering notes

repo_url: https://github.com/walchko/engineer_notebook

pages:
- ['index.md', 'Home', 'Welcome']
- ['arch_linux/archlinux.md', 'Arch Linux', 'Arch Linux']
- ['OSX/osx.md', 'OSX', 'OSX']
- ['OSX/cross-compiler-and-kernel.md', 'OSX', 'Cross Compiling']
- ['OSX/ssh.md', 'OSX', 'SSH']
- ['OSX/virtualbox.md', 'OSX', 'Virtualbox']
- ['raspbian/kernel.md', 'Raspbian', 'Linux kernel']
- ['raspbian/bluetooth.md', 'Raspbian', 'Bluetooth']
- ['raspbian/bt_sync.md', 'Raspbian', 'Bittorrent Sync']
- ['raspbian/git.md', 'Raspbian', 'Git']
- ['raspbian/i2c.md', 'Raspbian', 'I2C']
- ['raspbian/lan_protection.md', 'Raspbian', 'Lan Security Tools']
- ['raspbian/nodejs.md', 'Raspbian', 'Node.js']
- ['raspbian/python.md', 'Raspbian', 'Python']
- ['raspbian/rpi.md', 'Raspbian', 'RPi']
- ['raspbian/sd_card.md', 'Raspbian', 'SD Card']
- ['raspbian/services.md', 'Raspbian', 'Services']
- ['raspbian/ssh.md', 'Raspbian', 'SSH']
- ['raspbian/sw_updates.md', 'Raspbian', 'SW Updates']
- ['raspbian/usb_camera.md', 'Raspbian', 'USB Camera']
- ['raspbian/usb_hd.md', 'Raspbian', 'USB Hard Drive']
- ['raspbian/wifi.md', 'Raspbian', 'Wifi']
- ['engineering/statistics.md', 'Engineering','Statistics']
- ['engineering/ip_subnetting.md', 'Engineering','IP Subnetting']

copyright: Copyright &copy; 2015, Kevin J. Walchko
